
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 28 20:16:54 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 6;
  public static final int Parentesis_a = 5;
  public static final int Numero = 18;
  public static final int ERROR = 19;
  public static final int Identificador = 17;
  public static final int Comillas = 3;
  public static final int Llave_c = 9;
  public static final int Llave_a = 8;
  public static final int Coma = 13;
  public static final int P_coma = 14;
  public static final int T_dato = 4;
  public static final int Main = 10;
  public static final int EOF = 0;
  public static final int Diagonal = 7;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int P_reservada = 16;
  public static final int Op_logico = 15;
  public static final int Dos_puntos = 11;
  public static final int Dd_puntos = 12;
}

